import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'es' | 'en' | 'pt' | 'fr' | 'cn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  es: {
    // Navigation
    'nav.inicio': 'Inicio',
    'nav.arquitectura': 'Arquitectura',
    'nav.estructural': 'Ingeniería Estructural',
    'nav.instalaciones': 'Instalaciones',
    'nav.construccion': 'Construcción',
    'nav.informacion': 'Información',
    
    // Dropdown Option
    'nav.arquitectura.arquitectonico': 'Diseño arquitectónico',
    'nav.arquitectura.visual': 'Representación visual',
    'nav.estructural.sismorresistente': 'Sismorresistente',
    'nav.estructural.eolica': 'Eólica',
    'nav.instalaciones.sanitarias': 'Sanitarias',
    'nav.instalaciones.hidraulicas': 'Hidráulicas',
    'nav.instalaciones.electricas': 'Eléctricas',
    'nav.instalaciones.especiales': 'Especiales',
    'nav.construccion.civil': 'Civil',
    'nav.construccion.industrial': 'Industrial',
    'nav.informacion.proyectos': 'Proyectos',
    'nav.informacion.contacto': 'Contacto',
    'nav.informacion.nosotros': 'Sobre Nosotros',
    
    // Language names
    'language.es': 'Español',
    'language.en': 'Ingles',
    'language.pt': 'Portugues',
    'language.fr': 'Frances',
    'language.cn': 'Chino',
    
    // Home Page
    'home.hero.title': 'Mauro Muñoz y Alvaro May Construcciones',
    'home.hero.subtitle': 'Soy un ingeniero civil con más de 6 meses de experiencia en proyectos residenciales y comerciales.',
    'home.hero.button.quote': 'Solicitar Presupuesto',
    'home.hero.button.learn': 'Conoce Más',
    'home.services.title': 'Mis Servicios',
    'home.services.subtitle': 'Ofrezco una amplia gama de servicios de construcción para satisfacer todas tus necesidades',
    'home.services.residential.title': 'Construcción Residencial',
    'home.services.residential.description': 'Casas, condominios y proyectos habitacionales con los más altos estándares de calidad.',
    'home.services.residential.item1': 'Diseño arquitectónico personalizado',
    'home.services.residential.item2': 'Construcción llave en mano',
    'home.services.residential.item3': 'Remodelaciones y ampliaciones',
    'home.services.commercial.title': 'Construcción Comercial',
    'home.services.commercial.description': 'Oficinas, locales comerciales y naves industriales adaptadas a las necesidades de tu negocio.',
    'home.services.commercial.item1': 'Edificios de oficinas',
    'home.services.commercial.item2': 'Centros comerciales',
    'home.services.commercial.item3': 'Instalaciones industriales',
    'home.services.consulting.title': 'Consultoría y Diseño',
    'home.services.consulting.description': 'Asesoramiento profesional desde la planificación hasta la ejecución de tu proyecto.',
    'home.services.consulting.item1': 'Estudios de factibilidad',
    'home.services.consulting.item2': 'Gestión de permisos',
    'home.services.consulting.item3': 'Supervisión de obra',
    'home.why.title': '¿Por Qué Elegirnos?',
    'home.why.subtitle': 'Me destaco por mi experiencia, calidad y compromiso con cada proyecto',
    'home.why.experience': '+6 Meses',
    'home.why.experience.desc': 'De experiencia en el sector',
    'home.why.projects': '+5 Proyectos',
    'home.why.projects.desc': 'Completados exitosamente',
    'home.why.quality': 'Calidad Garantizada',
    'home.why.quality.desc': 'Materiales de primera calidad',
    'home.cta.title': '¿Listo para Comenzar tu Proyecto?',
    'home.cta.subtitle': 'Contáctame hoy y recibe una consulta gratuita para tu proyecto de construcción',
    'home.cta.button': 'Contactar Ahora',
    
    // About Page
    'about.hero.title': 'Sobre Nosotros',
    'about.hero.subtitle': 'Conoce nuestra experiencia y compromiso con la excelencia en construcción',
    'about.story.title': 'Mi Historia',
    'about.story.subtitle': 'Un camino de dedicación y crecimiento profesional',
    'about.story.paragraph1': 'Comenzamos nuestras carreras en ingeniería civil y arquitectura con una pasión inquebrantable por crear espacios que transformen vidas. Desde nuestros primeros proyectos, nos hemos dedicado a combinar la técnica más avanzada con un enfoque humano y personalizado.',
    'about.story.paragraph2': 'Nuestra experiencia abarca desde pequeñas remodelaciones residenciales hasta complejos proyectos comerciales, siempre manteniendo los más altos estándares de calidad y cumplimiento de plazos.',
    'about.story.paragraph3': 'Cada proyecto representa una oportunidad de crecer, aprender y entregar algo excepcional que supere las expectativas de nuestros clientes.',
    'about.story.foundation': 'Año de fundación',
    'about.story.completed': 'Proyectos completados',
    'about.story.employees': 'Empleados',
    'about.story.months': 'Meses de experiencia',
    'about.mission.title': 'Misión',
    'about.mission.text': 'Transformar ideas en realidades construidas, ofreciendo servicios de construcción e ingeniería de la más alta calidad, con un enfoque en la innovación, sostenibilidad y satisfacción total del cliente.',
    'about.vision.title': 'Visión',
    'about.vision.text': 'Ser reconocidos como ingenieros civiles y arquitectos de referencia en la región, liderando proyectos que marquen la diferencia en el desarrollo urbano y la calidad de vida de las comunidades.',
    'about.values.title': 'Valores',
    'about.values.integrity.title': 'Integridad',
    'about.values.integrity.desc': 'Honestidad y transparencia en cada proyecto',
    'about.values.excellence.title': 'Excelencia',
    'about.values.excellence.desc': 'Compromiso con la más alta calidad',
    'about.values.innovation.title': 'Innovación',
    'about.values.innovation.desc': 'Técnicas y materiales de vanguardia',
    'about.values.customer.title': 'Orientación al Cliente',
    'about.values.customer.desc': 'Tu satisfacción es nuestra prioridad',
    'about.certifications.title': 'Certificaciones y Logros',
    'about.certifications.subtitle': 'Respaldado por la educación y experiencia profesional',
    'about.certifications.degree': 'Ingeniería Civil',
    'about.certifications.degree.desc': 'Universidad Tecnologica',
    'about.certifications.experience': 'Experiencia Práctica',
    'about.certifications.experience.desc': 'Más de 24 meses en proyectos diversos',
    'about.certifications.training': 'Capacitación Continua',
    'about.certifications.training.desc': 'Actualización constante en normativas',
    'about.certifications.safety': 'Seguridad Industrial',
    'about.certifications.safety.desc': 'Certificado en protocolos de seguridad',
    'about.team.title': 'Mi Equipo',
    'about.team.subtitle': 'Un equipo multidisciplinario de profesionales comprometidos con la excelencia',
    'about.team.architects': 'Arquitectos',
    'about.team.architects.desc': 'Profesionales creativos que diseñan espacios funcionales y estéticamente atractivos',
    'about.team.engineers': 'Ingenieros',
    'about.team.engineers.desc': 'Especialistas en estructuras, instalaciones y gestión de proyectos de construcción',
    'about.team.foremen': 'Maestros de Obra',
    'about.team.foremen.desc': 'Expertos constructores con años de experiencia que garantizan la calidad en cada detalle',
    'about.cta.title': '¿Quieres ser Parte de Mis Próximos Proyectos?',
    'about.cta.subtitle': 'Contactanos y descubre cómo podemos hacer realidad tu proyecto de construcción',
    'about.cta.button': 'Solicitar Información',
    
    // Projects Page
    'projects.hero.title': 'Mis Proyectos',
    'projects.hero.subtitle': 'Descubre algunos de los proyectos que he realizado con calidad y dedicación',
    'projects.gallery.title': 'Galería de Proyectos',
    'projects.gallery.subtitle': 'Cada proyecto es único y refleja mi compromiso con la excelencia y la atención al detalle',
    'projects.cta.title': '¿Tienes un proyecto en mente?',
    'projects.cta.subtitle': 'Me encantaría conocer tu idea y ayudarte a hacerla realidad con la misma calidad y dedicación',
    'projects.cta.button': 'Solicitar Presupuesto Gratuito',
    'projects.moreInfo': 'Más Información',
    
    // Project Data
    'project.casa-moderna.title': 'Casa Residencial Moderna',
    'project.casa-moderna.description': 'Construcción de casa familiar de 200m² con diseño contemporáneo, acabados de lujo y jardín.',
    'project.oficina.title': 'Remodelación de Oficina',
    'project.oficina.description': 'Remodelación completa de oficina comercial con espacios abiertos y acabados modernos.',
    'project.ampliacion.title': 'Ampliación Residencial',
    'project.ampliacion.description': 'Ampliación de vivienda existente con nueva recámara, baño completo y área de estar.',
    
    // Contact Page
    'contact.hero.title': 'Contactame',
    'contact.hero.subtitle': 'Estoy listo para hacer realidad tu proyecto de construcción. Solicita tu presupuesto gratuito',
    'contact.form.title': 'Solicitar Presupuesto',
    'contact.form.subtitle': 'Completa el formulario y me pongo en contacto contigo en menos de 24 horas',
    'contact.form.name': 'Nombre Completo',
    'contact.form.name.placeholder': 'Tu nombre completo',
    'contact.form.email': 'Email',
    'contact.form.email.placeholder': 'tu@email.com',
    'contact.form.phone': 'Teléfono',
    'contact.form.phone.placeholder': '+52 55 1234 5678',
    'contact.form.project-type': 'Tipo de Proyecto',
    'contact.form.project-type.placeholder': 'Selecciona el tipo de proyecto',
    'contact.form.project-type.casa': 'Casa Residencial',
    'contact.form.project-type.departamento': 'Departamento',
    'contact.form.project-type.oficina': 'Oficina',
    'contact.form.project-type.comercial': 'Local Comercial',
    'contact.form.project-type.industrial': 'Nave Industrial',
    'contact.form.project-type.remodelacion': 'Remodelación',
    'contact.form.project-type.otro': 'Otro',
    'contact.form.message': 'Descripción del Proyecto',
    'contact.form.message.placeholder': 'Describe tu proyecto, ubicación, presupuesto estimado, y cualquier detalle importante...',
    'contact.form.send': 'Enviar Solicitud',
    'contact.info.title': 'Información de Contacto',
    'contact.info.phone': 'Teléfono',
    'contact.info.phone.schedule': 'Lunes a Viernes: 8:00 AM - 6:00 PM',
    'contact.info.email': 'Email',
    'contact.info.email.response': 'Respuesta en menos de 24 horas',
    'contact.info.office': 'Oficina',
    'contact.info.schedule': 'Horarios de Atención',
    'contact.info.schedule.weekdays': 'Lunes a Viernes: 8:00 AM - 6:00 PM',
    'contact.info.schedule.saturday': 'Sábados: 9:00 AM - 2:00 PM',
    'contact.why.title': '¿Por qué elegirme?',
    'contact.why.free-quote': 'Presupuesto gratuito y sin compromiso',
    'contact.why.experience': 'Más de 6 meses de experiencia',
    'contact.why.warranty': 'Garantía en todos mis trabajos',
    'contact.why.materials': 'Materiales de primera calidad',
    'contact.why.delivery': 'Cumplimiento de plazos garantizado',
    'contact.consultation.title': '¡Consulta Gratuita!',
    'contact.consultation.subtitle': 'Agenda una cita para discutir tu proyecto sin ningún costo',
    'contact.consultation.button': 'Agendar Cita',
    'contact.location.title': 'Nuestra Ubicación',
    'contact.location.subtitle': 'Visítanos en nuestra oficina central',
    
    // Footer
    'footer.text': 'Elaborado por Issac Nolberto Pacheco Ek',
  },
  en: {
    // Navigation
    'nav.inicio': 'Home',
    'nav.arquitectura': 'Architecture',
    'nav.estructural': 'Structural Engineering',
    'nav.instalaciones': 'Installations',
    'nav.construccion': 'Construction',
    'nav.informacion': 'Information',
    // Dropdown Option
    'nav.arquitectura.arquitectonico': 'Architectural Design',
    'nav.arquitectura.visual': 'Visual Representation',
    'nav.estructural.sismorresistente': 'Earthquake Resistant',
    'nav.estructural.eolica': 'Wind Engineering',
    'nav.instalaciones.sanitarias': 'Sanitary',
    'nav.instalaciones.hidraulicas': 'Hydraulic',
    'nav.instalaciones.electricas': 'Electrical',
    'nav.instalaciones.especiales': 'Special',
    'nav.construccion.civil': 'Civil',
    'nav.construccion.industrial': 'Industrial',
    'nav.informacion.proyectos': 'Projects',
    'nav.informacion.contacto': 'Contact',
    'nav.informacion.nosotros': 'About Us',
    // Language names
    'language.es': 'Spanish',
    'language.en': 'English',
    'language.pt': 'Portuguese',
    'language.fr': 'French',
    'language.cn': 'Chinese',
    // Home Page
    'home.hero.title': 'Mauro Muñoz and Alvaro May Constructions',
    'home.hero.subtitle': 'I am a civil engineer with over 6 months of experience in residential and commercial projects.',
    'home.hero.button.quote': 'Request a Quote',
    'home.hero.button.learn': 'Learn More',
    'home.services.title': 'My Services',
    'home.services.subtitle': 'I offer a wide range of construction services to meet all your needs',
    'home.services.residential.title': 'Residential Construction',
    'home.services.residential.description': 'Houses, condominiums, and housing projects with the highest quality standards.',
    'home.services.residential.item1': 'Custom architectural design',
    'home.services.residential.item2': 'Turnkey construction',
    'home.services.residential.item3': 'Remodeling and expansions',
    'home.services.commercial.title': 'Commercial Construction',
    'home.services.commercial.description': 'Offices, commercial premises, and industrial warehouses tailored to your business needs.',
    'home.services.commercial.item1': 'Office buildings',
    'home.services.commercial.item2': 'Shopping centers',
    'home.services.commercial.item3': 'Industrial facilities',
    'home.services.consulting.title': 'Consulting and Design',
    'home.services.consulting.description': 'Professional advice from planning to execution of your project.',
    'home.services.consulting.item1': 'Feasibility studies',
    'home.services.consulting.item2': 'Permit management',
    'home.services.consulting.item3': 'Construction supervision',
    'home.why.title': 'Why Choose Us?',
    'home.why.subtitle': 'I stand out for my experience, quality, and commitment to each project',
    'home.why.experience': '+6 Months',
    'home.why.experience.desc': 'Of experience in the sector',
    'home.why.projects': '+5 Projects',
    'home.why.projects.desc': 'Successfully completed',
    'home.why.quality': 'Guaranteed Quality',
    'home.why.quality.desc': 'Top quality materials',
    'home.cta.title': 'Ready to Start Your Project?',
    'home.cta.subtitle': 'Contact me today and get a free consultation for your construction project',
    'home.cta.button': 'Contact Now',
    // About Page
    'about.hero.title': 'About Us',
    'about.hero.subtitle': 'Learn about our experience and commitment to excellence in construction',
    'about.story.title': 'My Story',
    'about.story.subtitle': 'A path of dedication and professional growth',
    'about.story.paragraph1': 'We began our careers in civil engineering and architecture with an unwavering passion for creating spaces that transform lives. From our first projects, we have been dedicated to combining the most advanced techniques with a human and personalized approach.',
    'about.story.paragraph2': 'Our experience ranges from small residential renovations to complex commercial projects, always maintaining the highest standards of quality and meeting deadlines.',
    'about.story.paragraph3': 'Each project represents an opportunity to grow, learn, and deliver something exceptional that exceeds our clients’ expectations.',
    'about.story.foundation': 'Year of foundation',
    'about.story.completed': 'Completed projects',
    'about.story.employees': 'Employees',
    'about.story.months': 'Months of experience',
    'about.mission.title': 'Mission',
    'about.mission.text': 'To transform ideas into built realities, offering the highest quality construction and engineering services, with a focus on innovation, sustainability, and total customer satisfaction.',
    'about.vision.title': 'Vision',
    'about.vision.text': 'To be recognized as leading civil engineers and architects in the region, leading projects that make a difference in urban development and the quality of life of communities.',
    'about.values.title': 'Values',
    'about.values.integrity.title': 'Integrity',
    'about.values.integrity.desc': 'Honesty and transparency in every project',
    'about.values.excellence.title': 'Excellence',
    'about.values.excellence.desc': 'Commitment to the highest quality',
    'about.values.innovation.title': 'Innovation',
    'about.values.innovation.desc': 'Cutting-edge techniques and materials',
    'about.values.customer.title': 'Customer Focus',
    'about.values.customer.desc': 'Your satisfaction is our priority',
    'about.certifications.title': 'Certifications and Achievements',
    'about.certifications.subtitle': 'Backed by education and professional experience',
    'about.certifications.degree': 'Civil Engineering',
    'about.certifications.degree.desc': 'Technological University',
    'about.certifications.experience': 'Practical Experience',
    'about.certifications.experience.desc': 'Over 24 months in various projects',
    'about.certifications.training': 'Continuous Training',
    'about.certifications.training.desc': 'Constant updating on regulations',
    'about.certifications.safety': 'Industrial Safety',
    'about.certifications.safety.desc': 'Certified in safety protocols',
    'about.team.title': 'My Team',
    'about.team.subtitle': 'A multidisciplinary team of professionals committed to excellence',
    'about.team.architects': 'Architects',
    'about.team.architects.desc': 'Creative professionals who design functional and aesthetically pleasing spaces',
    'about.team.engineers': 'Engineers',
    'about.team.engineers.desc': 'Specialists in structures, installations, and construction project management',
    'about.team.foremen': 'Foremen',
    'about.team.foremen.desc': 'Expert builders with years of experience who guarantee quality in every detail',
    'about.cta.title': 'Do You Want to Be Part of My Next Projects?',
    'about.cta.subtitle': 'Contact us and discover how we can make your construction project a reality',
    'about.cta.button': 'Request Information',
    // Projects Page
    'projects.hero.title': 'My Projects',
    'projects.hero.subtitle': 'Discover some of the projects I have completed with quality and dedication',
    'projects.gallery.title': 'Project Gallery',
    'projects.gallery.subtitle': 'Each project is unique and reflects my commitment to excellence and attention to detail',
    'projects.cta.title': 'Do you have a project in mind?',
    'projects.cta.subtitle': 'I would love to hear your idea and help you make it a reality with the same quality and dedication',
    'projects.cta.button': 'Request Free Quote',
    'projects.moreInfo': 'More Information',
    // Project Data
    'project.casa-moderna.title': 'Modern Residential House',
    'project.casa-moderna.description': 'Construction of a 200m² family house with contemporary design, luxury finishes, and garden.',
    'project.oficina.title': 'Office Renovation',
    'project.oficina.description': 'Complete renovation of a commercial office with open spaces and modern finishes.',
    'project.ampliacion.title': 'Residential Expansion',
    'project.ampliacion.description': 'Expansion of an existing home with a new bedroom, full bathroom, and living area.',
    // Contact Page
    'contact.hero.title': 'Contact Me',
    'contact.hero.subtitle': 'I am ready to make your construction project a reality. Request your free quote',
    'contact.form.title': 'Request Quote',
    'contact.form.subtitle': 'Fill out the form and I will contact you in less than 24 hours',
    'contact.form.name': 'Full Name',
    'contact.form.name.placeholder': 'Your full name',
    'contact.form.email': 'Email',
    'contact.form.email.placeholder': 'your@email.com',
    'contact.form.phone': 'Phone',
    'contact.form.phone.placeholder': '+1 555 123 4567',
    'contact.form.project-type': 'Project Type',
    'contact.form.project-type.placeholder': 'Select the type of project',
    'contact.form.project-type.casa': 'Residential House',
    'contact.form.project-type.departamento': 'Apartment',
    'contact.form.project-type.oficina': 'Office',
    'contact.form.project-type.comercial': 'Commercial Premises',
    'contact.form.project-type.industrial': 'Industrial Warehouse',
    'contact.form.project-type.remodelacion': 'Remodeling',
    'contact.form.project-type.otro': 'Other',
    'contact.form.message': 'Project Description',
    'contact.form.message.placeholder': 'Describe your project, location, estimated budget, and any important details...',
    'contact.form.send': 'Send Request',
    'contact.info.title': 'Contact Information',
    'contact.info.phone': 'Phone',
    'contact.info.phone.schedule': 'Monday to Friday: 8:00 AM - 6:00 PM',
    'contact.info.email': 'Email',
    'contact.info.email.response': 'Response in less than 24 hours',
    'contact.info.office': 'Office',
    'contact.info.schedule': 'Business Hours',
    'contact.info.schedule.weekdays': 'Monday to Friday: 8:00 AM - 6:00 PM',
    'contact.info.schedule.saturday': 'Saturdays: 9:00 AM - 2:00 PM',
    'contact.why.title': 'Why choose me?',
    'contact.why.free-quote': 'Free and no-obligation quote',
    'contact.why.experience': 'Over 6 months of experience',
    'contact.why.warranty': 'Warranty on all my work',
    'contact.why.materials': 'Top quality materials',
    'contact.why.delivery': 'Guaranteed deadlines',
    'contact.consultation.title': 'Free Consultation!',
    'contact.consultation.subtitle': 'Schedule an appointment to discuss your project at no cost',
    'contact.consultation.button': 'Schedule Appointment',
    'contact.location.title': 'Our Location',
    'contact.location.subtitle': 'Visit us at our main office',
    // Footer
    'footer.text': 'Created by Issac Nolberto Pacheco Ek',
  },
  pt: {
    // Navigation
    'nav.inicio': 'Início',
    'nav.arquitectura': 'Arquitetura',
    'nav.estructural': 'Engenharia Estrutural',
    'nav.instalaciones': 'Instalações',
    'nav.construccion': 'Construção',
    'nav.informacion': 'Informação',
    // Dropdown Option
    'nav.arquitectura.arquitectonico': 'Design Arquitetônico',
    'nav.arquitectura.visual': 'Representação Visual',
    'nav.estructural.sismorresistente': 'Resistente a Terremotos',
    'nav.estructural.eolica': 'Engenharia Eólica',
    'nav.instalaciones.sanitarias': 'Sanitárias',
    'nav.instalaciones.hidraulicas': 'Hidráulicas',
    'nav.instalaciones.electricas': 'Elétricas',
    'nav.instalaciones.especiales': 'Especiais',
    'nav.construccion.civil': 'Civil',
    'nav.construccion.industrial': 'Industrial',
    'nav.informacion.proyectos': 'Projetos',
    'nav.informacion.contacto': 'Contato',
    'nav.informacion.nosotros': 'Sobre Nós',
    // Language names
    'language.es': 'Espanhol',
    'language.en': 'Inglês',
    'language.pt': 'Português',
    'language.fr': 'Francês',
    'language.cn': 'Chinês',
    // Home Page
    'home.hero.title': 'Mauro Muñoz e Alvaro May Construções',
    'home.hero.subtitle': 'Sou engenheiro civil com mais de 6 meses de experiência em projetos residenciais e comerciais.',
    'home.hero.button.quote': 'Solicitar Orçamento',
    'home.hero.button.learn': 'Saiba Mais',
    'home.services.title': 'Meus Serviços',
    'home.services.subtitle': 'Ofereço uma ampla gama de serviços de construção para atender a todas as suas necessidades',
    'home.services.residential.title': 'Construção Residencial',
    'home.services.residential.description': 'Casas, condomínios e projetos habitacionais com os mais altos padrões de qualidade.',
    'home.services.residential.item1': 'Design arquitetônico personalizado',
    'home.services.residential.item2': 'Construção turnkey',
    'home.services.residential.item3': 'Reformas e ampliações',
    'home.services.commercial.title': 'Construção Comercial',
    'home.services.commercial.description': 'Escritórios, lojas comerciais e galpões industriais adaptados às necessidades do seu negócio.',
    'home.services.commercial.item1': 'Prédios de escritórios',
    'home.services.commercial.item2': 'Centros comerciais',
    'home.services.commercial.item3': 'Instalações industriais',
    'home.services.consulting.title': 'Consultoria e Design',
    'home.services.consulting.description': 'Assessoria profissional desde o planejamento até a execução do seu projeto.',
    'home.services.consulting.item1': 'Estudos de viabilidade',
    'home.services.consulting.item2': 'Gestão de licenças',
    'home.services.consulting.item3': 'Supervisão de obra',
    'home.why.title': 'Por Que Nos Escolher?',
    'home.why.subtitle': 'Me destaco pela experiência, qualidade e compromisso com cada projeto',
    'home.why.experience': '+6 Meses',
    'home.why.experience.desc': 'De experiência no setor',
    'home.why.projects': '+5 Projetos',
    'home.why.projects.desc': 'Concluídos com sucesso',
    'home.why.quality': 'Qualidade Garantida',
    'home.why.quality.desc': 'Materiais de primeira qualidade',
    'home.cta.title': 'Pronto para Começar seu Projeto?',
    'home.cta.subtitle': 'Entre em contato hoje e receba uma consulta gratuita para seu projeto de construção',
    'home.cta.button': 'Contatar Agora',
    // About Page
    'about.hero.title': 'Sobre Nós',
    'about.hero.subtitle': 'Conheça nossa experiência e compromisso com a excelência na construção',
    'about.story.title': 'Minha História',
    'about.story.subtitle': 'Um caminho de dedicação e crescimento profissional',
    'about.story.paragraph1': 'Começamos nossas carreiras em engenharia civil e arquitetura com uma paixão inabalável por criar espaços que transformam vidas. Desde nossos primeiros projetos, nos dedicamos a combinar a técnica mais avançada com um enfoque humano e personalizado.',
    'about.story.paragraph2': 'Nossa experiência abrange desde pequenas reformas residenciais até complexos projetos comerciais, sempre mantendo os mais altos padrões de qualidade e cumprimento de prazos.',
    'about.story.paragraph3': 'Cada projeto representa uma oportunidade de crescer, aprender e entregar algo excepcional que supere as expectativas dos nossos clientes.',
    'about.story.foundation': 'Ano de fundação',
    'about.story.completed': 'Projetos concluídos',
    'about.story.employees': 'Funcionários',
    'about.story.months': 'Meses de experiência',
    'about.mission.title': 'Missão',
    'about.mission.text': 'Transformar ideias em realidades construídas, oferecendo serviços de construção e engenharia da mais alta qualidade, com foco em inovação, sustentabilidade e total satisfação do cliente.',
    'about.vision.title': 'Visão',
    'about.vision.text': 'Ser reconhecidos como engenheiros civis e arquitetos de referência na região, liderando projetos que fazem a diferença no desenvolvimento urbano e na qualidade de vida das comunidades.',
    'about.values.title': 'Valores',
    'about.values.integrity.title': 'Integridade',
    'about.values.integrity.desc': 'Honestidade e transparência em cada projeto',
    'about.values.excellence.title': 'Excelência',
    'about.values.excellence.desc': 'Compromisso com a mais alta qualidade',
    'about.values.innovation.title': 'Inovação',
    'about.values.innovation.desc': 'Técnicas e materiais de ponta',
    'about.values.customer.title': 'Foco no Cliente',
    'about.values.customer.desc': 'Sua satisfação é nossa prioridade',
    'about.certifications.title': 'Certificações e Conquistas',
    'about.certifications.subtitle': 'Respaldado pela educação e experiência profissional',
    'about.certifications.degree': 'Engenharia Civil',
    'about.certifications.degree.desc': 'Universidade Tecnológica',
    'about.certifications.experience': 'Experiência Prática',
    'about.certifications.experience.desc': 'Mais de 24 meses em projetos diversos',
    'about.certifications.training': 'Capacitação Contínua',
    'about.certifications.training.desc': 'Atualização constante em normas',
    'about.certifications.safety': 'Segurança Industrial',
    'about.certifications.safety.desc': 'Certificado em protocolos de segurança',
    'about.team.title': 'Minha Equipe',
    'about.team.subtitle': 'Uma equipe multidisciplinar de profissionais comprometidos com a excelência',
    'about.team.architects': 'Arquitetos',
    'about.team.architects.desc': 'Profissionais criativos que projetam espaços funcionais e esteticamente atraentes',
    'about.team.engineers': 'Engenheiros',
    'about.team.engineers.desc': 'Especialistas em estruturas, instalações e gestão de projetos de construção',
    'about.team.foremen': 'Mestres de Obra',
    'about.team.foremen.desc': 'Construtores experientes que garantem a qualidade em cada detalhe',
    'about.cta.title': 'Quer Fazer Parte dos Meus Próximos Projetos?',
    'about.cta.subtitle': 'Entre em contato e descubra como podemos realizar seu projeto de construção',
    'about.cta.button': 'Solicitar Informação',
    // Projects Page
    'projects.hero.title': 'Meus Projetos',
    'projects.hero.subtitle': 'Descubra alguns dos projetos que realizei com qualidade e dedicação',
    'projects.gallery.title': 'Galeria de Projetos',
    'projects.gallery.subtitle': 'Cada projeto é único e reflete meu compromisso com a excelência e atenção aos detalhes',
    'projects.cta.title': 'Tem um projeto em mente?',
    'projects.cta.subtitle': 'Adoraria conhecer sua ideia e ajudá-lo a realizá-la com a mesma qualidade e dedicação',
    'projects.cta.button': 'Solicitar Orçamento Gratuito',
    'projects.moreInfo': 'Mais Informações',
    // Project Data
    'project.casa-moderna.title': 'Casa Residencial Moderna',
    'project.casa-moderna.description': 'Construção de casa familiar de 200m² com design contemporâneo, acabamentos de luxo e jardim.',
    'project.oficina.title': 'Reforma de Escritório',
    'project.oficina.description': 'Reforma completa de escritório comercial com espaços abertos e acabamentos modernos.',
    'project.ampliacion.title': 'Ampliação Residencial',
    'project.ampliacion.description': 'Ampliação de residência existente com novo quarto, banheiro completo e área de estar.',
    // Contact Page
    'contact.hero.title': 'Contate-me',
    'contact.hero.subtitle': 'Estou pronto para realizar seu projeto de construção. Solicite seu orçamento gratuito',
    'contact.form.title': 'Solicitar Orçamento',
    'contact.form.subtitle': 'Preencha o formulário e entrarei em contato em menos de 24 horas',
    'contact.form.name': 'Nome Completo',
    'contact.form.name.placeholder': 'Seu nome completo',
    'contact.form.email': 'Email',
    'contact.form.email.placeholder': 'seu@email.com',
    'contact.form.phone': 'Telefone',
    'contact.form.phone.placeholder': '+55 11 1234 5678',
    'contact.form.project-type': 'Tipo de Projeto',
    'contact.form.project-type.placeholder': 'Selecione o tipo de projeto',
    'contact.form.project-type.casa': 'Casa Residencial',
    'contact.form.project-type.departamento': 'Apartamento',
    'contact.form.project-type.oficina': 'Escritório',
    'contact.form.project-type.comercial': 'Loja Comercial',
    'contact.form.project-type.industrial': 'Galpão Industrial',
    'contact.form.project-type.remodelacion': 'Reforma',
    'contact.form.project-type.otro': 'Outro',
    'contact.form.message': 'Descrição do Projeto',
    'contact.form.message.placeholder': 'Descreva seu projeto, localização, orçamento estimado e qualquer detalhe importante...',
    'contact.form.send': 'Enviar Solicitação',
    'contact.info.title': 'Informações de Contato',
    'contact.info.phone': 'Telefone',
    'contact.info.phone.schedule': 'Segunda a Sexta: 8:00 - 18:00',
    'contact.info.email': 'Email',
    'contact.info.email.response': 'Resposta em menos de 24 horas',
    'contact.info.office': 'Escritório',
    'contact.info.schedule': 'Horário de Atendimento',
    'contact.info.schedule.weekdays': 'Segunda a Sexta: 8:00 - 18:00',
    'contact.info.schedule.saturday': 'Sábados: 9:00 - 14:00',
    'contact.why.title': 'Por que me escolher?',
    'contact.why.free-quote': 'Orçamento gratuito e sem compromisso',
    'contact.why.experience': 'Mais de 6 meses de experiência',
    'contact.why.warranty': 'Garantia em todos os meus trabalhos',
    'contact.why.materials': 'Materiais de primeira qualidade',
    'contact.why.delivery': 'Cumprimento de prazos garantido',
    'contact.consultation.title': 'Consulta Gratuita!',
    'contact.consultation.subtitle': 'Agende uma reunião para discutir seu projeto sem custo',
    'contact.consultation.button': 'Agendar Reunião',
    'contact.location.title': 'Nossa Localização',
    'contact.location.subtitle': 'Visite-nos em nosso escritório central',
    // Footer
    'footer.text': 'Criado por Issac Nolberto Pacheco Ek',
  },
  fr: {
    // Navigation
    'nav.inicio': 'Accueil',
    'nav.arquitectura': 'Architecture',
    'nav.estructural': 'Ingénierie Structurelle',
    'nav.instalaciones': 'Installations',
    'nav.construccion': 'Construction',
    'nav.informacion': 'Information',
    // Dropdown Option
    'nav.arquitectura.arquitectonico': 'Conception Architecturale',
    'nav.arquitectura.visual': 'Représentation Visuelle',
    'nav.estructural.sismorresistente': 'Résistant aux Séismes',
    'nav.estructural.eolica': 'Ingénierie Éolienne',
    'nav.instalaciones.sanitarias': 'Sanitaires',
    'nav.instalaciones.hidraulicas': 'Hydrauliques',
    'nav.instalaciones.electricas': 'Électriques',
    'nav.instalaciones.especiales': 'Spéciales',
    'nav.construccion.civil': 'Civil',
    'nav.construccion.industrial': 'Industriel',
    'nav.informacion.proyectos': 'Projets',
    'nav.informacion.contacto': 'Contact',
    'nav.informacion.nosotros': 'À Propos',
    // Language names
    'language.es': 'Espagnol',
    'language.en': 'Anglais',
    'language.pt': 'Portugais',
    'language.fr': 'Français',
    'language.cn': 'Chinois',
    // Home Page
    'home.hero.title': 'Mauro Muñoz et Alvaro May Constructions',
    'home.hero.subtitle': 'Je suis ingénieur civil avec plus de 6 mois d’expérience dans des projets résidentiels et commerciaux.',
    'home.hero.button.quote': 'Demander un devis',
    'home.hero.button.learn': 'En savoir plus',
    'home.services.title': 'Mes Services',
    'home.services.subtitle': 'J’offre une large gamme de services de construction pour répondre à tous vos besoins',
    'home.services.residential.title': 'Construction Résidentielle',
    'home.services.residential.description': 'Maisons, appartements et projets résidentiels avec les plus hauts standards de qualité.',
    'home.services.residential.item1': 'Conception architecturale personnalisée',
    'home.services.residential.item2': 'Construction clé en main',
    'home.services.residential.item3': 'Rénovations et extensions',
    'home.services.commercial.title': 'Construction Commerciale',
    'home.services.commercial.description': 'Bureaux, locaux commerciaux et entrepôts industriels adaptés aux besoins de votre entreprise.',
    'home.services.commercial.item1': 'Immeubles de bureaux',
    'home.services.commercial.item2': 'Centres commerciaux',
    'home.services.commercial.item3': 'Installations industrielles',
    'home.services.consulting.title': 'Conseil et Conception',
    'home.services.consulting.description': 'Conseil professionnel de la planification à l’exécution de votre projet.',
    'home.services.consulting.item1': 'Études de faisabilité',
    'home.services.consulting.item2': 'Gestion des permis',
    'home.services.consulting.item3': 'Supervision des travaux',
    'home.why.title': 'Pourquoi Nous Choisir ?',
    'home.why.subtitle': 'Je me distingue par mon expérience, ma qualité et mon engagement pour chaque projet',
    'home.why.experience': '+6 Mois',
    'home.why.experience.desc': 'D’expérience dans le secteur',
    'home.why.projects': '+5 Projets',
    'home.why.projects.desc': 'Réalisés avec succès',
    'home.why.quality': 'Qualité Garantie',
    'home.why.quality.desc': 'Matériaux de première qualité',
    'home.cta.title': 'Prêt à commencer votre projet ?',
    'home.cta.subtitle': 'Contactez-moi aujourd’hui et recevez une consultation gratuite pour votre projet de construction',
    'home.cta.button': 'Contacter Maintenant',
    // About Page
    'about.hero.title': 'À Propos',
    'about.hero.subtitle': 'Découvrez notre expérience et notre engagement envers l’excellence en construction',
    'about.story.title': 'Mon Histoire',
    'about.story.subtitle': 'Un parcours de dévouement et de croissance professionnelle',
    'about.story.paragraph1': 'Nous avons commencé nos carrières en ingénierie civile et en architecture avec une passion inébranlable pour créer des espaces qui transforment des vies. Dès nos premiers projets, nous nous sommes consacrés à combiner la technique la plus avancée avec une approche humaine et personnalisée.',
    'about.story.paragraph2': 'Notre expérience va de petites rénovations résidentielles à des projets commerciaux complexes, tout en maintenant les plus hauts standards de qualité et de respect des délais.',
    'about.story.paragraph3': 'Chaque projet représente une opportunité de grandir, d’apprendre et de livrer quelque chose d’exceptionnel qui dépasse les attentes de nos clients.',
    'about.story.foundation': 'Année de fondation',
    'about.story.completed': 'Projets réalisés',
    'about.story.employees': 'Employés',
    'about.story.months': 'Mois d’expérience',
    'about.mission.title': 'Mission',
    'about.mission.text': 'Transformer les idées en réalités construites, en offrant des services de construction et d’ingénierie de la plus haute qualité, axés sur l’innovation, la durabilité et la satisfaction totale du client.',
    'about.vision.title': 'Vision',
    'about.vision.text': 'Être reconnus comme des ingénieurs civils et des architectes de référence dans la région, en dirigeant des projets qui font la différence dans le développement urbain et la qualité de vie des communautés.',
    'about.values.title': 'Valeurs',
    'about.values.integrity.title': 'Intégrité',
    'about.values.integrity.desc': 'Honnêteté et transparence dans chaque projet',
    'about.values.excellence.title': 'Excellence',
    'about.values.excellence.desc': 'Engagement envers la plus haute qualité',
    'about.values.innovation.title': 'Innovation',
    'about.values.innovation.desc': 'Techniques et matériaux de pointe',
    'about.values.customer.title': 'Orientation Client',
    'about.values.customer.desc': 'Votre satisfaction est notre priorité',
    'about.certifications.title': 'Certifications et Réalisations',
    'about.certifications.subtitle': 'Soutenu par l’éducation et l’expérience professionnelle',
    'about.certifications.degree': 'Génie Civil',
    'about.certifications.degree.desc': 'Université Technologique',
    'about.certifications.experience': 'Expérience Pratique',
    'about.certifications.experience.desc': 'Plus de 24 mois sur divers projets',
    'about.certifications.training': 'Formation Continue',
    'about.certifications.training.desc': 'Mise à jour constante des réglementations',
    'about.certifications.safety': 'Sécurité Industrielle',
    'about.certifications.safety.desc': 'Certifié en protocoles de sécurité',
    'about.team.title': 'Mon Équipe',
    'about.team.subtitle': 'Une équipe pluridisciplinaire de professionnels engagés dans l’excellence',
    'about.team.architects': 'Architectes',
    'about.team.architects.desc': 'Professionnels créatifs qui conçoivent des espaces fonctionnels et esthétiques',
    'about.team.engineers': 'Ingénieurs',
    'about.team.engineers.desc': 'Spécialistes des structures, installations et gestion de projets de construction',
    'about.team.foremen': 'Chefs de Chantier',
    'about.team.foremen.desc': 'Constructeurs expérimentés qui garantissent la qualité dans chaque détail',
    'about.cta.title': 'Voulez-vous faire partie de mes prochains projets ?',
    'about.cta.subtitle': 'Contactez-nous et découvrez comment nous pouvons réaliser votre projet de construction',
    'about.cta.button': 'Demander des Informations',
    // Projects Page
    'projects.hero.title': 'Mes Projets',
    'projects.hero.subtitle': 'Découvrez certains des projets que j’ai réalisés avec qualité et dévouement',
    'projects.gallery.title': 'Galerie de Projets',
    'projects.gallery.subtitle': 'Chaque projet est unique et reflète mon engagement envers l’excellence et l’attention aux détails',
    'projects.cta.title': 'Vous avez un projet en tête ?',
    'projects.cta.subtitle': 'Je serais ravi de connaître votre idée et de vous aider à la réaliser avec la même qualité et le même dévouement',
    'projects.cta.button': 'Demander un devis gratuit',
    'projects.moreInfo': 'Plus d’informations',
    // Project Data
    'project.casa-moderna.title': 'Maison Résidentielle Moderne',
    'project.casa-moderna.description': 'Construction d’une maison familiale de 200m² au design contemporain, finitions de luxe et jardin.',
    'project.oficina.title': 'Rénovation de Bureau',
    'project.oficina.description': 'Rénovation complète d’un bureau commercial avec des espaces ouverts et des finitions modernes.',
    'project.ampliacion.title': 'Extension Résidentielle',
    'project.ampliacion.description': 'Extension d’une maison existante avec une nouvelle chambre, une salle de bain complète et un espace de vie.',
    // Contact Page
    'contact.hero.title': 'Contactez-moi',
    'contact.hero.subtitle': 'Je suis prêt à réaliser votre projet de construction. Demandez votre devis gratuit',
    'contact.form.title': 'Demander un devis',
    'contact.form.subtitle': 'Remplissez le formulaire et je vous contacterai en moins de 24 heures',
    'contact.form.name': 'Nom Complet',
    'contact.form.name.placeholder': 'Votre nom complet',
    'contact.form.email': 'Email',
    'contact.form.email.placeholder': 'votre@email.com',
    'contact.form.phone': 'Téléphone',
    'contact.form.phone.placeholder': '+33 1 23 45 67 89',
    'contact.form.project-type': 'Type de Projet',
    'contact.form.project-type.placeholder': 'Sélectionnez le type de projet',
    'contact.form.project-type.casa': 'Maison Résidentielle',
    'contact.form.project-type.departamento': 'Appartement',
    'contact.form.project-type.oficina': 'Bureau',
    'contact.form.project-type.comercial': 'Local Commercial',
    'contact.form.project-type.industrial': 'Entrepôt Industriel',
    'contact.form.project-type.remodelacion': 'Rénovation',
    'contact.form.project-type.otro': 'Autre',
    'contact.form.message': 'Description du Projet',
    'contact.form.message.placeholder': 'Décrivez votre projet, emplacement, budget estimé et tout détail important...',
    'contact.form.send': 'Envoyer la Demande',
    'contact.info.title': 'Informations de Contact',
    'contact.info.phone': 'Téléphone',
    'contact.info.phone.schedule': 'Lundi à Vendredi : 8h00 - 18h00',
    'contact.info.email': 'Email',
    'contact.info.email.response': 'Réponse en moins de 24 heures',
    'contact.info.office': 'Bureau',
    'contact.info.schedule': 'Horaires d’Ouverture',
    'contact.info.schedule.weekdays': 'Lundi à Vendredi : 8h00 - 18h00',
    'contact.info.schedule.saturday': 'Samedis : 9h00 - 14h00',
    'contact.why.title': 'Pourquoi me choisir ?',
    'contact.why.free-quote': 'Devis gratuit et sans engagement',
    'contact.why.experience': 'Plus de 6 mois d’expérience',
    'contact.why.warranty': 'Garantie sur tous mes travaux',
    'contact.why.materials': 'Matériaux de première qualité',
    'contact.why.delivery': 'Délais garantis',
    'contact.consultation.title': 'Consultation Gratuite !',
    'contact.consultation.subtitle': 'Prenez rendez-vous pour discuter de votre projet sans frais',
    'contact.consultation.button': 'Prendre Rendez-vous',
    'contact.location.title': 'Notre Emplacement',
    'contact.location.subtitle': 'Venez nous rendre visite à notre bureau principal',
    // Footer
    'footer.text': 'Créé par Issac Nolberto Pacheco Ek',
  },
  cn: {
    // Navigation
    'nav.inicio': '首页',
    'nav.arquitectura': '建筑',
    'nav.estructural': '结构工程',
    'nav.instalaciones': '设施安装',
    'nav.construccion': '施工建设',
    'nav.informacion': '信息',
    // Dropdown Option
    'nav.arquitectura.arquitectonico': '建筑设计',
    'nav.arquitectura.visual': '视觉呈现',
    'nav.estructural.sismorresistente': '抗震',
    'nav.estructural.eolica': '风力工程',
    'nav.instalaciones.sanitarias': '卫生设施',
    'nav.instalaciones.hidraulicas': '水力设施',
    'nav.instalaciones.electricas': '电气设施',
    'nav.instalaciones.especiales': '特殊设施',
    'nav.construccion.civil': '民用建筑',
    'nav.construccion.industrial': '工业建筑',
    'nav.informacion.proyectos': '项目',
    'nav.informacion.contacto': '联系',
    'nav.informacion.nosotros': '关于我们',
    // Language names
    'language.es': '西班牙语',
    'language.en': '英语',
    'language.pt': '葡萄牙语',
    'language.fr': '法语',
    'language.cn': '中文',
    // Home Page
    'home.hero.title': '毛罗·穆尼奥斯与阿尔瓦罗·梅建筑',
    'home.hero.subtitle': '我是一名拥有6个月以上住宅和商业项目经验的土木工程师。',
    'home.hero.button.quote': '申请报价',
    'home.hero.button.learn': '了解更多',
    'home.services.title': '我的服务',
    'home.services.subtitle': '我提供广泛的建筑服务，满足您的所有需求',
    'home.services.residential.title': '住宅建设',
    'home.services.residential.description': '房屋、公寓和高标准住宅项目。',
    'home.services.residential.item1': '个性化建筑设计',
    'home.services.residential.item2': '交钥匙工程',
    'home.services.residential.item3': '翻新与扩建',
    'home.services.commercial.title': '商业建设',
    'home.services.commercial.description': '办公室、商业场所和工业厂房，满足您的业务需求。',
    'home.services.commercial.item1': '办公楼',
    'home.services.commercial.item2': '购物中心',
    'home.services.commercial.item3': '工业设施',
    'home.services.consulting.title': '咨询与设计',
    'home.services.consulting.description': '从规划到执行为您的项目提供专业建议。',
    'home.services.consulting.item1': '可行性研究',
    'home.services.consulting.item2': '许可证管理',
    'home.services.consulting.item3': '工程监督',
    'home.why.title': '为什么选择我们？',
    'home.why.subtitle': '我以经验、质量和对每个项目的承诺而脱颖而出',
    'home.why.experience': '+6个月',
    'home.why.experience.desc': '行业经验',
    'home.why.projects': '+5个项目',
    'home.why.projects.desc': '成功完成',
    'home.why.quality': '质量保证',
    'home.why.quality.desc': '优质材料',
    'home.cta.title': '准备开始您的项目了吗？',
    'home.cta.subtitle': '立即联系我，免费获得您的建筑项目咨询',
    'home.cta.button': '立即联系',
    // About Page
    'about.hero.title': '关于我们',
    'about.hero.subtitle': '了解我们在建筑领域的经验和对卓越的承诺',
    'about.story.title': '我的故事',
    'about.story.subtitle': '奉献与专业成长之路',
    'about.story.paragraph1': '我们以坚定不移的热情开始了土木工程和建筑事业，致力于创造改变生活的空间。从最初的项目开始，我们就致力于将最先进的技术与人性化和个性化的方法相结合。',
    'about.story.paragraph2': '我们的经验涵盖从小型住宅翻新到复杂的商业项目，始终保持最高的质量标准和按时交付。',
    'about.story.paragraph3': '每个项目都是成长、学习和交付超越客户期望的卓越成果的机会。',
    'about.story.foundation': '成立年份',
    'about.story.completed': '已完成项目',
    'about.story.employees': '员工',
    'about.story.months': '经验月数',
    'about.mission.title': '使命',
    'about.mission.text': '将想法变为现实，提供最高质量的建筑和工程服务，注重创新、可持续性和客户的完全满意。',
    'about.vision.title': '愿景',
    'about.vision.text': '成为该地区领先的土木工程师和建筑师，领导对城市发展和社区生活质量产生影响的项目。',
    'about.values.title': '价值观',
    'about.values.integrity.title': '诚信',
    'about.values.integrity.desc': '每个项目都诚实透明',
    'about.values.excellence.title': '卓越',
    'about.values.excellence.desc': '承诺最高质量',
    'about.values.innovation.title': '创新',
    'about.values.innovation.desc': '前沿技术与材料',
    'about.values.customer.title': '以客户为中心',
    'about.values.customer.desc': '您的满意是我们的首要任务',
    'about.certifications.title': '认证与成就',
    'about.certifications.subtitle': '拥有教育和专业经验的支持',
    'about.certifications.degree': '土木工程',
    'about.certifications.degree.desc': '技术大学',
    'about.certifications.experience': '实践经验',
    'about.certifications.experience.desc': '24个月以上的各类项目经验',
    'about.certifications.training': '持续培训',
    'about.certifications.training.desc': '规范的持续更新',
    'about.certifications.safety': '工业安全',
    'about.certifications.safety.desc': '安全协议认证',
    'about.team.title': '我的团队',
    'about.team.subtitle': '一支致力于卓越的多学科专业团队',
    'about.team.architects': '建筑师',
    'about.team.architects.desc': '设计功能性和美观空间的创意专业人士',
    'about.team.engineers': '工程师',
    'about.team.engineers.desc': '结构、设施和建筑项目管理专家',
    'about.team.foremen': '工头',
    'about.team.foremen.desc': '经验丰富的建造者，确保每个细节的质量',
    'about.cta.title': '想参与我的下一个项目吗？',
    'about.cta.subtitle': '联系我们，了解我们如何实现您的建筑项目',
    'about.cta.button': '申请信息',
    // Projects Page
    'projects.hero.title': '我的项目',
    'projects.hero.subtitle': '发现我以质量和奉献完成的一些项目',
    'projects.gallery.title': '项目画廊',
    'projects.gallery.subtitle': '每个项目都是独一无二的，体现了我对卓越和细节的关注',
    'projects.cta.title': '有项目想法吗？',
    'projects.cta.subtitle': '我很乐意听取您的想法，并以同样的质量和奉献帮助您实现',
    'projects.cta.button': '申请免费报价',
    'projects.moreInfo': '更多信息',
    // Project Data
    'project.casa-moderna.title': '现代住宅',
    'project.casa-moderna.description': '建造200平方米的家庭住宅，采用现代设计、豪华装修和花园。',
    'project.oficina.title': '办公室翻新',
    'project.oficina.description': '对商业办公室进行全面翻新，设有开放空间和现代化装修。',
    'project.ampliacion.title': '住宅扩建',
    'project.ampliacion.description': '对现有住宅进行扩建，新增卧室、全套浴室和起居区。',
    // Contact Page
    'contact.hero.title': '联系我',
    'contact.hero.subtitle': '我已准备好实现您的建筑项目。申请免费报价',
    'contact.form.title': '申请报价',
    'contact.form.subtitle': '填写表格，我会在24小时内与您联系',
    'contact.form.name': '全名',
    'contact.form.name.placeholder': '您的全名',
    'contact.form.email': '电子邮件',
    'contact.form.email.placeholder': 'your@email.com',
    'contact.form.phone': '电话',
    'contact.form.phone.placeholder': '+86 10 1234 5678',
    'contact.form.project-type': '项目类型',
    'contact.form.project-type.placeholder': '选择项目类型',
    'contact.form.project-type.casa': '住宅',
    'contact.form.project-type.departamento': '公寓',
    'contact.form.project-type.oficina': '办公室',
    'contact.form.project-type.comercial': '商业场所',
    'contact.form.project-type.industrial': '工业厂房',
    'contact.form.project-type.remodelacion': '翻新',
    'contact.form.project-type.otro': '其他',
    'contact.form.message': '项目描述',
    'contact.form.message.placeholder': '描述您的项目、位置、预算和任何重要细节...',
    'contact.form.send': '发送申请',
    'contact.info.title': '联系信息',
    'contact.info.phone': '电话',
    'contact.info.phone.schedule': '周一至周五：8:00-18:00',
    'contact.info.email': '电子邮件',
    'contact.info.email.response': '24小时内回复',
    'contact.info.office': '办公室',
    'contact.info.schedule': '办公时间',
    'contact.info.schedule.weekdays': '周一至周五：8:00-18:00',
    'contact.info.schedule.saturday': '周六：9:00-14:00',
    'contact.why.title': '为什么选择我？',
    'contact.why.free-quote': '免费且无义务报价',
    'contact.why.experience': '6个月以上经验',
    'contact.why.warranty': '所有工作均有保修',
    'contact.why.materials': '优质材料',
    'contact.why.delivery': '保证交付时间',
    'contact.consultation.title': '免费咨询！',
    'contact.consultation.subtitle': '预约讨论您的项目，无需任何费用',
    'contact.consultation.button': '预约',
    'contact.location.title': '我们的地址',
    'contact.location.subtitle': '欢迎来我们总部参观',
    // Footer
    'footer.text': '由 Issac Nolberto Pacheco Ek 制作',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('es');

  const t = (key: string): string => {
    const currentTranslations = translations[language] as any;
    return currentTranslations[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
