import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  es: {
    // Navigation
    'nav.inicio': 'Inicio',
    'nav.sobre-mi': 'Sobre mi',
    'nav.proyectos': 'Proyectos',
    'nav.contacto': 'Contacto',
    
    // Home Page
    'home.hero.title': 'Mauro Muñoz Construcciones',
    'home.hero.subtitle': 'Soy un ingeniero civil con más de 6 meses de experiencia en proyectos residenciales y comerciales.',
    'home.hero.button.quote': 'Solicitar Presupuesto',
    'home.hero.button.learn': 'Conoce Más',
    'home.services.title': 'Mis Servicios',
    'home.services.subtitle': 'Ofrezco una amplia gama de servicios de construcción para satisfacer todas tus necesidades',
    'home.services.residential.title': 'Construcción Residencial',
    'home.services.residential.description': 'Casas, condominios y proyectos habitacionales con los más altos estándares de calidad.',
    'home.services.residential.item1': 'Diseño arquitectónico personalizado',
    'home.services.residential.item2': 'Construcción llave en mano',
    'home.services.residential.item3': 'Remodelaciones y ampliaciones',
    'home.services.commercial.title': 'Construcción Comercial',
    'home.services.commercial.description': 'Oficinas, locales comerciales y naves industriales adaptadas a las necesidades de tu negocio.',
    'home.services.commercial.item1': 'Edificios de oficinas',
    'home.services.commercial.item2': 'Centros comerciales',
    'home.services.commercial.item3': 'Instalaciones industriales',
    'home.services.consulting.title': 'Consultoría y Diseño',
    'home.services.consulting.description': 'Asesoramiento profesional desde la planificación hasta la ejecución de tu proyecto.',
    'home.services.consulting.item1': 'Estudios de factibilidad',
    'home.services.consulting.item2': 'Gestión de permisos',
    'home.services.consulting.item3': 'Supervisión de obra',
    'home.why.title': '¿Por Qué Elegirnos?',
    'home.why.subtitle': 'Me destaco por mi experiencia, calidad y compromiso con cada proyecto',
    'home.why.experience': '+6 Meses',
    'home.why.experience.desc': 'De experiencia en el sector',
    'home.why.projects': '+5 Proyectos',
    'home.why.projects.desc': 'Completados exitosamente',
    'home.why.quality': 'Calidad Garantizada',
    'home.why.quality.desc': 'Materiales de primera calidad',
    'home.cta.title': '¿Listo para Comenzar tu Proyecto?',
    'home.cta.subtitle': 'Contáctame hoy y recibe una consulta gratuita para tu proyecto de construcción',
    'home.cta.button': 'Contactar Ahora',
    
    // About Page
    'about.hero.title': 'Sobre Mi',
    'about.hero.subtitle': 'Conoce mi experiencia y compromiso con la excelencia en construcción',
    'about.story.title': 'Mi Historia',
    'about.story.subtitle': 'Un camino de dedicación y crecimiento profesional',
    'about.story.paragraph1': 'Comencé mi carrera en la ingeniería civil con una pasión inquebrantable por crear espacios que transformen vidas. Desde mis primeros proyectos, me he dedicado a combinar la técnica más avanzada con un enfoque humano y personalizado.',
    'about.story.paragraph2': 'Mi experiencia abarca desde pequeñas remodelaciones residenciales hasta complejos proyectos comerciales, siempre manteniendo los más altos estándares de calidad y cumplimiento de plazos.',
    'about.story.paragraph3': 'Cada proyecto representa una oportunidad de crecer, aprender y entregar algo excepcional que supere las expectativas de mis clientes.',
    'about.story.foundation': 'Año de fundación',
    'about.story.completed': 'Proyectos completados',
    'about.story.employees': 'Empleados',
    'about.story.months': 'Meses de experiencia',
    'about.mission.title': 'Misión',
    'about.mission.text': 'Transformar ideas en realidades construidas, ofreciendo servicios de construcción e ingeniería de la más alta calidad, con un enfoque en la innovación, sostenibilidad y satisfacción total del cliente.',
    'about.vision.title': 'Visión',
    'about.vision.text': 'Ser reconocido como el ingeniero civil de referencia en la región, liderando proyectos que marquen la diferencia en el desarrollo urbano y la calidad de vida de las comunidades.',
    'about.values.title': 'Valores',
    'about.values.integrity.title': 'Integridad',
    'about.values.integrity.desc': 'Honestidad y transparencia en cada proyecto',
    'about.values.excellence.title': 'Excelencia',
    'about.values.excellence.desc': 'Compromiso con la más alta calidad',
    'about.values.innovation.title': 'Innovación',
    'about.values.innovation.desc': 'Técnicas y materiales de vanguardia',
    'about.values.customer.title': 'Orientación al Cliente',
    'about.values.customer.desc': 'Tu satisfacción es nuestra prioridad',
    'about.certifications.title': 'Certificaciones y Logros',
    'about.certifications.subtitle': 'Respaldado por la educación y experiencia profesional',
    'about.certifications.degree': 'Ingeniería Civil',
    'about.certifications.degree.desc': 'Universidad Autónoma de Yucatán',
    'about.certifications.experience': 'Experiencia Práctica',
    'about.certifications.experience.desc': 'Más de 6 meses en proyectos diversos',
    'about.certifications.training': 'Capacitación Continua',
    'about.certifications.training.desc': 'Actualización constante en normativas',
    'about.certifications.safety': 'Seguridad Industrial',
    'about.certifications.safety.desc': 'Certificado en protocolos de seguridad',
    'about.team.title': 'Mi Equipo',
    'about.team.subtitle': 'Un equipo multidisciplinario de profesionales comprometidos con la excelencia',
    'about.team.architects': 'Arquitectos',
    'about.team.architects.desc': 'Profesionales creativos que diseñan espacios funcionales y estéticamente atractivos',
    'about.team.engineers': 'Ingenieros',
    'about.team.engineers.desc': 'Especialistas en estructuras, instalaciones y gestión de proyectos de construcción',
    'about.team.foremen': 'Maestros de Obra',
    'about.team.foremen.desc': 'Expertos constructores con años de experiencia que garantizan la calidad en cada detalle',
    'about.cta.title': '¿Quieres ser Parte de Mis Próximos Proyectos?',
    'about.cta.subtitle': 'Contáctame y descubre cómo podemos hacer realidad tu proyecto de construcción',
    'about.cta.button': 'Solicitar Información',
    
    // Projects Page
    'projects.hero.title': 'Mis Proyectos',
    'projects.hero.subtitle': 'Descubre algunos de los proyectos que he realizado con calidad y dedicación',
    'projects.gallery.title': 'Galería de Proyectos',
    'projects.gallery.subtitle': 'Cada proyecto es único y refleja mi compromiso con la excelencia y la atención al detalle',
    'projects.cta.title': '¿Tienes un proyecto en mente?',
    'projects.cta.subtitle': 'Me encantaría conocer tu idea y ayudarte a hacerla realidad con la misma calidad y dedicación',
    'projects.cta.button': 'Solicitar Presupuesto Gratuito',
    
    // Project Data
    'project.casa-moderna.title': 'Casa Residencial Moderna',
    'project.casa-moderna.description': 'Construcción de casa familiar de 200m² con diseño contemporáneo, acabados de lujo y jardín.',
    'project.oficina.title': 'Remodelación de Oficina',
    'project.oficina.description': 'Remodelación completa de oficina comercial con espacios abiertos y acabados modernos.',
    'project.ampliacion.title': 'Ampliación Residencial',
    'project.ampliacion.description': 'Ampliación de vivienda existente con nueva recámara, baño completo y área de estar.',
    
    // Contact Page
    'contact.hero.title': 'Contactame',
    'contact.hero.subtitle': 'Estoy listo para hacer realidad tu proyecto de construcción. Solicita tu presupuesto gratuito',
    'contact.form.title': 'Solicitar Presupuesto',
    'contact.form.subtitle': 'Completa el formulario y me pongo en contacto contigo en menos de 24 horas',
    'contact.form.name': 'Nombre Completo',
    'contact.form.name.placeholder': 'Tu nombre completo',
    'contact.form.email': 'Email',
    'contact.form.email.placeholder': 'tu@email.com',
    'contact.form.phone': 'Teléfono',
    'contact.form.phone.placeholder': '+52 55 1234 5678',
    'contact.form.project-type': 'Tipo de Proyecto',
    'contact.form.project-type.placeholder': 'Selecciona el tipo de proyecto',
    'contact.form.project-type.casa': 'Casa Residencial',
    'contact.form.project-type.departamento': 'Departamento',
    'contact.form.project-type.oficina': 'Oficina',
    'contact.form.project-type.comercial': 'Local Comercial',
    'contact.form.project-type.industrial': 'Nave Industrial',
    'contact.form.project-type.remodelacion': 'Remodelación',
    'contact.form.project-type.otro': 'Otro',
    'contact.form.message': 'Descripción del Proyecto',
    'contact.form.message.placeholder': 'Describe tu proyecto, ubicación, presupuesto estimado, y cualquier detalle importante...',
    'contact.form.send': 'Enviar Solicitud',
    'contact.info.title': 'Información de Contacto',
    'contact.info.phone': 'Teléfono',
    'contact.info.phone.schedule': 'Lunes a Viernes: 8:00 AM - 6:00 PM',
    'contact.info.email': 'Email',
    'contact.info.email.response': 'Respuesta en menos de 24 horas',
    'contact.info.office': 'Oficina',
    'contact.info.schedule': 'Horarios de Atención',
    'contact.info.schedule.weekdays': 'Lunes a Viernes: 8:00 AM - 6:00 PM',
    'contact.info.schedule.saturday': 'Sábados: 9:00 AM - 2:00 PM',
    'contact.why.title': '¿Por qué elegirme?',
    'contact.why.free-quote': 'Presupuesto gratuito y sin compromiso',
    'contact.why.experience': 'Más de 6 meses de experiencia',
    'contact.why.warranty': 'Garantía en todos mis trabajos',
    'contact.why.materials': 'Materiales de primera calidad',
    'contact.why.delivery': 'Cumplimiento de plazos garantizado',
    'contact.consultation.title': '¡Consulta Gratuita!',
    'contact.consultation.subtitle': 'Agenda una cita para discutir tu proyecto sin ningún costo',
    'contact.consultation.button': 'Agendar Cita',
    'contact.location.title': 'Mi Ubicación',
    'contact.location.subtitle': 'Visítanos en mi oficina central',
    
    // Footer
    'footer.text': 'Elaborado por Issac Nolberto Pacheco Ek',
  },
  en: {
    // Navigation
    'nav.inicio': 'Home',
    'nav.sobre-mi': 'About Me',
    'nav.proyectos': 'Projects',
    'nav.contacto': 'Contact',
    
    // Home Page
    'home.hero.title': 'Mauro Muñoz Construction',
    'home.hero.subtitle': 'I am a civil engineer with more than 6 months of experience in residential and commercial projects.',
    'home.hero.button.quote': 'Request Quote',
    'home.hero.button.learn': 'Learn More',
    'home.services.title': 'My Services',
    'home.services.subtitle': 'I offer a wide range of construction services to meet all your needs',
    'home.services.residential.title': 'Residential Construction',
    'home.services.residential.description': 'Houses, condominiums and housing projects with the highest quality standards.',
    'home.services.residential.item1': 'Custom architectural design',
    'home.services.residential.item2': 'Turnkey construction',
    'home.services.residential.item3': 'Renovations and extensions',
    'home.services.commercial.title': 'Commercial Construction',
    'home.services.commercial.description': 'Offices, commercial premises and industrial buildings adapted to your business needs.',
    'home.services.commercial.item1': 'Office buildings',
    'home.services.commercial.item2': 'Shopping centers',
    'home.services.commercial.item3': 'Industrial facilities',
    'home.services.consulting.title': 'Consulting and Design',
    'home.services.consulting.description': 'Professional advice from planning to execution of your project.',
    'home.services.consulting.item1': 'Feasibility studies',
    'home.services.consulting.item2': 'Permit management',
    'home.services.consulting.item3': 'Construction supervision',
    'home.why.title': 'Why Choose Us?',
    'home.why.subtitle': 'I stand out for my experience, quality and commitment to each project',
    'home.why.experience': '+6 Months',
    'home.why.experience.desc': 'Of experience in the sector',
    'home.why.projects': '+5 Projects',
    'home.why.projects.desc': 'Successfully completed',
    'home.why.quality': 'Quality Guaranteed',
    'home.why.quality.desc': 'First quality materials',
    'home.cta.title': 'Ready to Start Your Project?',
    'home.cta.subtitle': 'Contact me today and receive a free consultation for your construction project',
    'home.cta.button': 'Contact Now',
    
    // About Page
    'about.hero.title': 'About Me',
    'about.hero.subtitle': 'Learn about my experience and commitment to excellence in construction',
    'about.story.title': 'My Story',
    'about.story.subtitle': 'A path of dedication and professional growth',
    'about.story.paragraph1': 'I began my career in civil engineering with an unwavering passion for creating spaces that transform lives. Since my first projects, I have dedicated myself to combining the most advanced techniques with a human and personalized approach.',
    'about.story.paragraph2': 'My experience ranges from small residential renovations to complex commercial projects, always maintaining the highest standards of quality and deadline compliance.',
    'about.story.paragraph3': 'Each project represents an opportunity to grow, learn and deliver something exceptional that exceeds my clients\' expectations.',
    'about.story.foundation': 'Year of foundation',
    'about.story.completed': 'Completed projects',
    'about.story.employees': 'Employees',
    'about.story.months': 'Months of experience',
    'about.mission.title': 'Mission',
    'about.mission.text': 'Transform ideas into built realities, offering construction and engineering services of the highest quality, with a focus on innovation, sustainability and total customer satisfaction.',
    'about.vision.title': 'Vision',
    'about.vision.text': 'To be recognized as the reference civil engineer in the region, leading projects that make a difference in urban development and quality of life of communities.',
    'about.values.title': 'Values',
    'about.values.integrity.title': 'Integrity',
    'about.values.integrity.desc': 'Honesty and transparency in every project',
    'about.values.excellence.title': 'Excellence',
    'about.values.excellence.desc': 'Commitment to the highest quality',
    'about.values.innovation.title': 'Innovation',
    'about.values.innovation.desc': 'Cutting-edge techniques and materials',
    'about.values.customer.title': 'Customer Orientation',
    'about.values.customer.desc': 'Your satisfaction is our priority',
    'about.certifications.title': 'Certifications and Achievements',
    'about.certifications.subtitle': 'Backed by education and professional experience',
    'about.certifications.degree': 'Civil Engineering',
    'about.certifications.degree.desc': 'Autonomous University of Yucatan',
    'about.certifications.experience': 'Practical Experience',
    'about.certifications.experience.desc': 'More than 6 months in diverse projects',
    'about.certifications.training': 'Continuous Training',
    'about.certifications.training.desc': 'Constant updating in regulations',
    'about.certifications.safety': 'Industrial Safety',
    'about.certifications.safety.desc': 'Certified in safety protocols',
    'about.team.title': 'My Team',
    'about.team.subtitle': 'A multidisciplinary team of professionals committed to excellence',
    'about.team.architects': 'Architects',
    'about.team.architects.desc': 'Creative professionals who design functional and aesthetically appealing spaces',
    'about.team.engineers': 'Engineers',
    'about.team.engineers.desc': 'Specialists in structures, installations and construction project management',
    'about.team.foremen': 'Foremen',
    'about.team.foremen.desc': 'Expert builders with years of experience who guarantee quality in every detail',
    'about.cta.title': 'Want to be Part of My Next Projects?',
    'about.cta.subtitle': 'Contact me and discover how we can make your construction project a reality',
    'about.cta.button': 'Request Information',
    
    // Projects Page
    'projects.hero.title': 'My Projects',
    'projects.hero.subtitle': 'Discover some of the projects I have completed with quality and dedication',
    'projects.gallery.title': 'Project Gallery',
    'projects.gallery.subtitle': 'Each project is unique and reflects my commitment to excellence and attention to detail',
    'projects.cta.title': 'Do you have a project in mind?',
    'projects.cta.subtitle': 'I would love to know your idea and help you make it a reality with the same quality and dedication',
    'projects.cta.button': 'Request Free Quote',
    
    // Project Data
    'project.casa-moderna.title': 'Modern Residential House',
    'project.casa-moderna.description': 'Construction of 200m² family house with contemporary design, luxury finishes and garden.',
    'project.oficina.title': 'Office Renovation',
    'project.oficina.description': 'Complete renovation of commercial office with open spaces and modern finishes.',
    'project.ampliacion.title': 'Residential Extension',
    'project.ampliacion.description': 'Extension of existing home with new bedroom, full bathroom and living area.',
    
    // Contact Page
    'contact.hero.title': 'Contact Me',
    'contact.hero.subtitle': 'I am ready to make your construction project a reality. Request your free quote',
    'contact.form.title': 'Request Quote',
    'contact.form.subtitle': 'Fill out the form and I will contact you in less than 24 hours',
    'contact.form.name': 'Full Name',
    'contact.form.name.placeholder': 'Your full name',
    'contact.form.email': 'Email',
    'contact.form.email.placeholder': 'your@email.com',
    'contact.form.phone': 'Phone',
    'contact.form.phone.placeholder': '+1 55 1234 5678',
    'contact.form.project-type': 'Project Type',
    'contact.form.project-type.placeholder': 'Select project type',
    'contact.form.project-type.casa': 'Residential House',
    'contact.form.project-type.departamento': 'Apartment',
    'contact.form.project-type.oficina': 'Office',
    'contact.form.project-type.comercial': 'Commercial Space',
    'contact.form.project-type.industrial': 'Industrial Building',
    'contact.form.project-type.remodelacion': 'Renovation',
    'contact.form.project-type.otro': 'Other',
    'contact.form.message': 'Project Description',
    'contact.form.message.placeholder': 'Describe your project, location, estimated budget, and any important details...',
    'contact.form.send': 'Send Request',
    'contact.info.title': 'Contact Information',
    'contact.info.phone': 'Phone',
    'contact.info.phone.schedule': 'Monday to Friday: 8:00 AM - 6:00 PM',
    'contact.info.email': 'Email',
    'contact.info.email.response': 'Response in less than 24 hours',
    'contact.info.office': 'Office',
    'contact.info.schedule': 'Business Hours',
    'contact.info.schedule.weekdays': 'Monday to Friday: 8:00 AM - 6:00 PM',
    'contact.info.schedule.saturday': 'Saturdays: 9:00 AM - 2:00 PM',
    'contact.why.title': 'Why choose me?',
    'contact.why.free-quote': 'Free quote with no commitment',
    'contact.why.experience': 'More than 6 months of experience',
    'contact.why.warranty': 'Warranty on all my work',
    'contact.why.materials': 'First quality materials',
    'contact.why.delivery': 'Guaranteed deadline compliance',
    'contact.consultation.title': 'Free Consultation!',
    'contact.consultation.subtitle': 'Schedule an appointment to discuss your project at no cost',
    'contact.consultation.button': 'Schedule Appointment',
    'contact.location.title': 'My Location',
    'contact.location.subtitle': 'Visit us at our main office',
    
    // Footer
    'footer.text': 'Created by Issac Nolberto Pacheco Ek',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('es');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['es']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
